#!/usr/bin/env Rscript
fklruic <- read.csv("/shared/cssamba0/staffstore/acm538/LRU4kInstructions.txt", header=TRUE)
tklruic <- read.csv("/shared/cssamba0/staffstore/acm538/LRU2kinstructions.txt", header=TRUE)
optic <- read.csv("/shared/cssamba0/staffstore/acm538/OPTinstructions.txt", header=TRUE)
fkcumsum<-data.frame(count=fklruic$Count, fkcumthreadsum=cumsum(rowSums(fklruic[,-1], na.rm=TRUE)))
tkcumsum<-data.frame(count=tklruic$Count, tkcumthreadsum=cumsum(rowSums(tklruic[,-1], na.rm=TRUE)))
opticcumsum<-data.frame(count=optic$Count, optthreadsum=cumsum(rowSums(optic[,-1], na.rm=TRUE)))
png("performance.png")
plot(y = fkcumsum$fkcumthreadsum, x=fklruic$Count, type="l", col="green", main="Partial execution of benchmark", sub="red for OPT, green for 4k LRU, yellow for 2k LRU", xlab="Simulated ticks", ylab="Lines processed", xlim=range(c(0, max(fklruic$Count))), ylim=(c(0, max(tkcumsum$tkcumthreadsum))))
par(new=TRUE)
plot(y=tkcumsum$tkcumthreadsum, x=tklruic$Count, col="yellow", axes=FALSE, xlab="", ylab="", xlim=range(c(0,max(fklruic$Count))), ylim=(c(0, max(tkcumsum$tkcumthreadsum))), type="l")
par(new=TRUE)
plot(y=opticcumsum$optthreadsum, x=optic$Count, col="red", axes=FALSE, xlab="", ylab="", xlim=range(c(0, max(fklruic$Count))), ylim=(c(0, max(tkcumsum$tkcumthreadsum))), type="l")
dev.off()
